# steps:
#   - name: Use the API key
#     env:
#         AI_KEY: ${{ secrets.AI_KEY }}
#       run:
#       #Use the API key

# steps:
#     - name: Hello world action
#       with: # Set the secret as an input
#           super_secret: ${{ secrets.AI_KEY }}
#       env: # Or as an environment variable
#           super_secret: ${{ secrets.AI_KEY }}

name: My Workflow
on: push

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install dependencies
              run: npm install
            - name: Run script
              env:
                  AI_KEY: ${{ secrets.AI_KEY }}
              run: node my-script.js
